version: '2'
services:
    motorsportsdatabase-app:
        image: motorsportsdatabase
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://motorsportsdatabase-mysql:3306/motorsportsdatabase?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://motorsportsdatabase-elasticsearch:9200
        ports:
            - 8080:8080
    motorsportsdatabase-mysql:
        extends:
            file: mysql.yml
            service: motorsportsdatabase-mysql
    motorsportsdatabase-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: motorsportsdatabase-elasticsearch
