export * from './driver-points-details.model';
export * from './driver-points-details-popup.service';
export * from './driver-points-details.service';
export * from './driver-points-details-dialog.component';
export * from './driver-points-details-delete-dialog.component';
export * from './driver-points-details-detail.component';
export * from './driver-points-details.component';
export * from './driver-points-series.component';
export * from './driver-points-details.route';
