/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

ALTER TABLE event
ADD COLUMN rally bit(1) DEFAULT NULL;

ALTER TABLE event_edition
ADD COLUMN location VARCHAR(50),
ADD COLUMN location_time_zone VARCHAR(255);

ALTER TABLE event_session
CHANGE COLUMN duration duration DECIMAL(5,2) NOT NULL ;
